version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:%2A7gzOMPcDco8l4If%3AO-CVb9Ehztq@database-1.cluster-cluyg244y2cj.eu-north-1.rds.amazonaws.com:5432/sabqcms
      - NEXTAUTH_SECRET=sabq-ai-cms-secret-key-2025
      - NEXTAUTH_URL=http://localhost:3000
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - sabq-network

  # خدمة Nginx للإنتاج (اختياري)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - sabq-network
    profiles:
      - production

networks:
  sabq-network:
    driver: bridge 