version: '3.8'

services:
  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sabq-ai-cms
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3000}
      - JWT_SECRET=${JWT_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./data:/app/data
    networks:
      - sabq-network
    depends_on:
      - redis

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: sabq-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - sabq-network
    command: redis-server --appendonly yes

  # Nginx Reverse Proxy (optional for production)
  nginx:
    image: nginx:alpine
    container_name: sabq-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./public/uploads:/usr/share/nginx/html/uploads:ro
    networks:
      - sabq-network
    depends_on:
      - app
    profiles:
      - production

networks:
  sabq-network:
    driver: bridge

volumes:
  redis-data:
    driver: local 