version: '3.8'

services:
  # التطبيق الرئيسي
  app:
    build:
      context: .
      dockerfile: Dockerfile.personal-server
    container_name: sabq-cms
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./logs:/app/logs
      - ./.env:/app/.env
    depends_on:
      - redis
    networks:
      - sabq-network

  # Redis للكاش
  redis:
    image: redis:7-alpine
    container_name: sabq-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - sabq-network
    command: redis-server --appendonly yes

  # Nginx كـ Reverse Proxy (اختياري)
  nginx:
    image: nginx:alpine
    container_name: sabq-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - app
    networks:
      - sabq-network

volumes:
  redis-data:
    driver: local

networks:
  sabq-network:
    driver: bridge 