name: sabq-ai-cms
region: nyc
services:
- name: web
  dockerfile_path: Dockerfile.digitalocean
  source_dir: /
  github:
    repo: sabq4org/sabq-ai-cms
    branch: main
    deploy_on_push: true
  build_command: |
    echo "🏗️ بناء المشروع..." && \
    npx prisma generate && \
    npm run build && \
    echo "✅ تم البناء بنجاح"
  run_command: |
    echo "🚀 تشغيل الخادم..." && \
    if [ -f ".next/BUILD_ID" ]; then \
      echo "✅ Build ID: $(cat .next/BUILD_ID)" && \
      npx next start -H 0.0.0.0 -p ${PORT:-3000}; \
    else \
      echo "❌ BUILD_ID مفقود! إعادة البناء..." && \
      npm run build && \
      npx next start -H 0.0.0.0 -p ${PORT:-3000}; \
    fi
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: professional-xs
  http_port: 3000
  health_check:
    http_path: /api/health
    initial_delay_seconds: 30
    period_seconds: 30
    timeout_seconds: 15
    success_threshold: 1
    failure_threshold: 5
  envs:
  # الإعدادات الأساسية
  - key: NODE_ENV
    value: production
  - key: NEXT_TELEMETRY_DISABLED
    value: "1"
  - key: SKIP_EMAIL_VERIFICATION
    value: "true"
  - key: PORT
    value: "3000"
  
  # قاعدة البيانات (استخدم DigitalOcean Secrets)
  - key: DATABASE_URL
    type: SECRET
    
  # المصادقة
  - key: NEXTAUTH_SECRET
    type: SECRET
  - key: JWT_SECRET
    type: SECRET
    
  # Cloudinary
  - key: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
    value: dybhezmvb
  - key: NEXT_PUBLIC_CLOUDINARY_API_KEY
    value: "559894124915114"
  - key: CLOUDINARY_API_SECRET
    type: SECRET
    
  # معلومات التطبيق
  - key: APP_VERSION
    value: "0.2.2"
  - key: APP_NAME
    value: "sabq-ai-cms"
    
  # إعدادات Node.js
  - key: NODE_OPTIONS
    value: "--max-old-space-size=1024"
  - key: PRISMA_CLI_BINARY_TARGETS
    value: '["debian-openssl-3.0.x"]' 