name: Optimize Images (lossless where possible)

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  optimize:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Optimize images
        uses: calibreapp/image-actions@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnlyChanged: true
          # Prefer lossless for PNG/SVG; conservative JPEG quality
          jpegQuality: 90
          webpQuality: 90
          # Ignore build artifacts and deps
          ignorePaths: |
            .next/**
            node_modules/**
            **/*.psd
            **/*.ai
            **/*.sketch

      - name: Commit and push changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(images): optimize images (lossless where possible)"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          push_options: "--force-with-lease"
