name: Deploy to AWS Lightsail

on:
  push:
    branches: [ production-branch ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Lightsail
      env:
        LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
        LIGHTSAIL_USERNAME: ${{ secrets.LIGHTSAIL_USERNAME }}
        LIGHTSAIL_KEY: ${{ secrets.LIGHTSAIL_KEY }}
      run: |
        echo "$LIGHTSAIL_KEY" > lightsail_key.pem
        chmod 600 lightsail_key.pem
        ssh -o StrictHostKeyChecking=no -i lightsail_key.pem $LIGHTSAIL_USERNAME@$LIGHTSAIL_HOST << 'EOF'
          cd ~/sabq-ai-cms
          git pull origin production-branch
          npm install
          npx prisma generate
          npm run build
          pm2 restart sabq
        EOF
        rm lightsail_key.pem 